[main]
# Выбор шрифта (лигатуры в foot работать НЕ БУДЕТ)
font=Fira Code:size=14
# Нативная поддержка Sixel включена по умолчанию, но можно уточнить
# terminal=foot

[colors]
# Прозрачность фона (0.0 — прозрачно, 1.0 — плотно)
alpha=0.8
# Пример темной цветовой схемы
background=000000

[cursor]
style=block
blink=yes

[mouse]
hide-when-typing=yes
